from logging import exception


class x:
    def __init__(self):
       self.n=int(input("enter a no"))
       print(self.name)
       
        
            
            
obj=x()                        
       